### ISSUE TITLE
cfmigration NOT in subsystems directory

### ISSUE THREAD

**Issue by ivanionut** [tonyjunkes/fw1-cfmigrations-example#1]
Hi @tonyjunkes,
I'm trying to integrate cfmigration with fw1, but without installing it in the subsystems directory, but in a `/com/cfmigrations/` directory

in the `/subsystems/` directory I write all the logic to do `up / down` migrations (in the`/ subsystems/ migrations/ `directory)

This is my `LoadListener.cfc`: https://gist.github.com/ivanionut/c9f8e0dbd2e4e8737d4601364dff0973

and this is the error I get: 
![fw1](https://user-images.githubusercontent.com/2210744/82751884-9a835e80-9dba-11ea-923e-c8fb6da435ab.png)

Do you have any suggestions for this error?
Thanks,
Ivan

**Comment by ivanionut** [comment]
mmmh, I think I solved it like this:

```
.declare("cfmigrations").instanceOf("cfmigrations.models.MigrationService").done()
.declare( "MigrationService" ).asValue(
	beanfactory.getBean( "cfmigrations" )
		.setDatasource( "my_datasource" )
		.setDefaultGrammar( "MySQLGrammar@qb" )
		.setMigrationsDirectory( "/resources/database/migrations" )
		.setMigrationsTable( "cfmigrations" )
		.setWireBox( beanfactory.getBean( "WireBox" ) )
).done()

```

do you think it's a good solution or can i improve it in a different way?

**Comment by tonyjunkes** [comment]
Hi @ivanionut,

I would need to try out a scenario like that myself but I do not see anything wrong with your approach.

**Comment by ivanionut** [comment]
Hi @tonyjunkes and thank you! 👍
